# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy package.json and install dependencies
COPY package*.json ./
RUN npm install

# Copy the rest of the application
COPY . .

# Expose port 3000 for client to run on
ENV PORT=3000
EXPOSE 3000

# Start the application
CMD [ "npm", "start" ]